### ISSUE TITLE
SublimeText 3

### ISSUE THREAD

**Issue by mikebywater** [mrdevon/RocketUnidata#6]
Are there any  plans to make this compatible with sublime text 3 ?

**Comment by mrdevon** [comment]
There are now!  I haven't started using Sublime Text 3 yet, so I will have to read up on any technical differences between 2 & 3 first.  I will try to do that within the week and then see if I can get an estimate on when I can get it done.

**Comment by mikebywater** [comment]
Fantastic let me know if you need any help, I am very interested using this, happy to help test or contribute in any way I can

**Comment by mrdevon** [comment]
I just tested installing the package for Sublime Text 3 and it appears to work exactly the same as Sublime Text 2.  I have updated the README accordingly.  I plan on getting this package submitted to be included into the official repositories soon so that people don't have to modify the Package Control user settings.
